[workspace]
semver_check = true
git_release_enable = false
files_to_ignore = ["examples/**"]

[[package]]
name = "lambda-integration-tests"
publish = false

[changelog]
protect_breaking_commits = true
